var Ls = {
  name: String, size: Number, type: String, created: String,
  dev:String,
  mode:String,
  nlink:String,
  uid:String,
  gid:String,
  rdev:String,
  blksize:String,
  ino:String,
  size:String,
  blocks:String,
  atimeMs:String,
  mtimeMs:String,
  ctimeMs:String,
  birthtimeMs:String,
  atime:String,
  mtime:String,
  ctime:String,
  birthtime:String,
}